### ISSUE TITLE
Questions/remarques/précisions sur les chapitres 1 à 3

### ISSUE THREAD

**Issue by Epithumia** [dav74/nsi_terminale#1]
Pour faire suite à Twitter, voici quelques points de réflexion que j'ai sur les chapitres de BD 👍 

- Dans l'introduction, il y a un point sur la duplication des données sur plusieurs machines. C'est intéressant, mais j'ai le sentiment que ça dépasse le cadre des SGBD. En particulier, le paragraphe se termine sur "C'est aussi les SGBD qui assurent la maintenance des différentes copies de la base de données."(*), mais dans la plupart des usages qu'ils rencontreront, ce n'est pas le cas. Par défaut, virtuellement aucun SGBDR ne s'occupe de ça si on ne le configure pas expressément pour, et sqlite3 n'en est pas capable. Bref, je ne sais pas si c'est le meilleur moment pour parler de problème de réplication/redondance de données, ni le plus pertinent. Sur mes serveurs, par exemple, la redondance ne vient pas du SGBD, mais du RAID et de sauvegardes périodiques.
- Dans le chapitre 3, il y a des choix éditoriaux, j'imagine. Le programme le mentionne comme possibilité, mais je ne vois pas de mention de DISTINCT ici (mais ORDER BY est présent). Il y a des sections "cours", "activités", "exercice", résumé", est-ce qu'une section "Pour aller plus loin" n'aurait pas sa place où cela pourrait être développé, ainsi que les agrégats simples (et les alias, par exemple) ?
- Dans le chapitre 3 toujours, dans le cours, point 4 et 5) : "du/le livre ayant pour titre Hypérion" dans les deux cas, strictement, ce sont "des/les livres ayant pour titre Hypérion". Là c'est un pet peeve, disons, mais je répète à mes étudiants de ne pas avoir de préjugés sur les données stockées s'il n'y a pas de règle de gestion explicite. Par exemple, si je ne dis pas explicitement le contraire, toutes les chaînes de caractères hors clefs sont susceptibles d'avoir des doublons (titres, noms, prénoms...). Pour un SELECT, au pire on a des résultats en trop ; pour un UPDATE/DELETE, ça peut être critique.

En tout cas merci pour tout le boulot, pour moi qui vais récupérer les NSI (en partie) dans le supérieur, ça me permet de voir ce qu'ils savent (en théorie).

(*) Une amie me reprend tout le temps sur "C'est les" qui pique grammaticalement : "Ce sont les".

**Comment by dav74** [comment]
Bonjour,
Un grand merci pour ce message, je vais réfléchir à la façon d'intégrer
toutes ces remarques.
Bonne soirée
David Roche

<http://gplus.to/DavidRoche>david_roche_publicKey.asc
<https://drive.google.com/file/d/0B-MgHHp_RGd-RTlHYnJOUkhlUlU/view?usp=sharing>


Le sam. 24 avr. 2021 à 20:03, Rafael Lopez ***@***.***> a
écrit :
